apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: healthcare-mcp-server
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # CPU and memory
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "1Gi"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - name: healthcare-mcp-server
        # This will be replaced during deployment
        image: gcr.io/PROJECT_ID/healthcare-mcp-server:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: GCP_PROJECT_ID
          value: "PROJECT_ID"  # Replace with actual project ID
        - name: BIGQUERY_DATASET_PREFIX
          value: "tuva_synthetic_data"  # Replace with your dataset prefix
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true
